# Generated by Django 5.1.2 on 2024-10-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_created_at_product_featured_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_filterable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.attribute'),
        ),
    ]
